import type { Badge, Category } from './types';

// Category definitions with display names and icons
export const categories: Category[] = [
  { id: 'code', name: 'Code Mastery', icon: '🧩' },
  { id: 'bugs', name: 'Bug Hunter', icon: '🐛' },
  { id: 'languages', name: 'Stack Surfer', icon: '🌐' },
  { id: 'mentor', name: 'Mentorship', icon: '🧠' },
  { id: 'ci', name: 'Code Inspector', icon: '🔍' },
  { id: 'creative', name: 'Documentation & Ideas', icon: '💡' },
  { id: 'points', name: 'Points Progression', icon: '⭐' },
  { id: 'lang_mastery', name: 'Language Competition', icon: '🏆' },
  { id: 'mastery', name: 'Streak Achievements', icon: '🔥' },
];

export const achievementData: Badge[] = [
  // Everyday Badges - Contribution Count
  {
    id: 1,
    title: 'Hello, Tinkerer',
    description: '1 Pull Request merged.',
    icon: '/Badges/Tinkerer 2.jpg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-10',
    category: 'code',
    position: 1,
  },
  {
    id: 2,
    title: 'Ninja Contributor',
    description: '5 Pull Requests merged.',
    icon: '/Badges/Ninja 1.jpg',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-12',
    category: 'code',
    position: 2,
    requires: [1],
  },
  {
    id: 3,
    title: 'Engineer Overclocked',
    description: '10 Pull Requests merged.',
    icon: '/Badges/Engineer OverClocked.jpeg',
    unlocked: true,
    tier: 'gold',
    date: '2025-05-14',
    category: 'code',
    position: 3,
    requires: [2],
  },
  {
    id: 4,
    title: 'Doomguy',
    description: '20 Pull Requests merged.',
    icon: '/Badges/DoomeGuy 2.jpg',
    unlocked: true,
    tier: 'diamond',
    date: '2025-05-15',
    category: 'code',
    position: 4,
    requires: [3],
  },

  // Everyday Badges - Reporting Bugs
  {
    id: 5,
    title: 'Sanitizer',
    description: 'Get 1 bug accepted (issue).',
    icon: '/Badges/Sanitizer.jpeg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-08',
    category: 'bugs',
    position: 1,
  },
  {
    id: 6,
    title: 'Pest Control',
    description: 'Get 5 bugs accepted (issue).',
    icon: '/Badges/Pest Control.jpeg',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-12',
    category: 'bugs',
    position: 2,
    requires: [5],
  },
  {
    id: 7,
    title: 'Planet Cleanser',
    description: 'Get 10 bugs accepted (issue).',
    icon: '/Badges/Planet Cleanser.jpeg',
    unlocked: true,
    tier: 'gold',
    date: '2025-05-14',
    category: 'bugs',
    position: 3,
    requires: [6],
  },

  // Everyday Badges - Different Technologies
  {
    id: 8,
    title: 'Polyglot',
    description: 'Contribute in 3 different languages.',
    icon: '/Badges/Polyglot 1.jpg',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-11',
    category: 'languages',
    position: 1,
  },
  {
    id: 9,
    title: 'Jack of All Stacks',
    description: 'Contribute in 5 different languages.',
    icon: '/Badges/Jack of all Stacks.jpg',
    unlocked: false,
    tier: 'gold',
    progress: 40,
    category: 'languages',
    position: 2,
    requires: [8],
  },

  // Everyday Badges - Discussion Help
  {
    id: 10,
    title: 'The Scholar',
    description: 'Help out 1 person with their issue solving (in group).',
    icon: '/Badges/Scholar.jpeg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-09',
    category: 'mentor',
    position: 1,
  },
  {
    id: 11,
    title: 'The Gulliver',
    description: 'Help out 3 people with issue solving (in group).',
    icon: '/Badges/Gulliver.jpeg',
    unlocked: false,
    tier: 'silver',
    progress: 30,
    category: 'mentor',
    position: 2,
    requires: [10],
  },
  {
    id: 12,
    title: 'The Oracle',
    description: 'Help out 5 people with issue solving (in group).',
    icon: '/Badges/Oracle.jpeg',
    unlocked: false,
    tier: 'gold',
    progress: 10,
    category: 'mentor',
    position: 3,
    requires: [11],
  },

  // Everyday Badges - Testing Contributions
  {
    id: 13,
    title: 'Lab Assistant',
    description: 'Get 1 testing related PR merged.',
    icon: '/Badges/Lab Assistant 1.jpeg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-07',
    category: 'ci',
    position: 1,
  },
  {
    id: 14,
    title: 'Quality Assurer',
    description: 'Get 5 testing related PRs merged.',
    icon: '/Badges/Quality Assurer 1.jpeg',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-10',
    category: 'ci',
    position: 2,
    requires: [13],
  },
  {
    id: 15,
    title: 'Full-Coded Alchemist',
    description: 'Contribute 10 testing related PRs.',
    icon: '/Badges/Full-Coded Alchemist 1.jpeg',
    unlocked: false,
    tier: 'gold',
    date: '2025-05-12',
    category: 'ci',
    position: 3,
    requires: [14],
  },

  // Everyday Badges - Others
  {
    id: 16,
    title: 'High Charity',
    description: 'Get 2 feature suggestions accepted.',
    icon: '/Badges/High Charity.jpeg',
    unlocked: false,
    tier: 'silver',
    progress: 10,
    category: 'creative',
    position: 1,
  },
  {
    id: 17,
    title: 'Zeppelin of Mighty Gargantuaness',
    description: 'Get a PR marked for High-Impact.',
    icon: '/Badges/ZOMG.jpg',
    unlocked: false,
    tier: 'gold',
    progress: 0,
    category: 'creative',
    position: 2,
  },
  {
    id: 18,
    title: 'Doc Champ',
    description: 'Get 2 documentation PRs accepted.',
    icon: '/Badges/DocChamp 1.jpg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-06',
    category: 'creative',
    position: 3,
  },
  {
    id: 19,
    title: 'Shaman',
    description: 'Reach 250 bounty points.',
    icon: '/Badges/shaman 1.jpg',
    unlocked: true,
    tier: 'bronze',
    date: '2025-05-06',
    category: 'points',
    position: 1,
  },
  {
    id: 20,
    title: 'Henchman',
    description: 'Reach 500 bounty points.',
    icon: '/Badges/Henchman 1.jpg',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-08',
    category: 'points',
    position: 2,
    requires: [19],
  },
  {
    id: 21,
    title: 'Kingpin',
    description: 'Reach 750 bounty points.',
    icon: '/Badges/King pin.jpg',
    unlocked: true,
    tier: 'gold',
    date: '2025-05-10',
    category: 'points',
    position: 3,
    requires: [20],
  },
  {
    id: 22,
    title: 'The Godfather',
    description: 'Reach 1000 bounty points.',
    icon: '/Badges/God Father 1.jpg',
    unlocked: false,
    tier: 'diamond',
    progress: 0,
    category: 'points',
    position: 4,
    requires: [21],
  },

  // Seasonal Badges - Rust
  {
    id: 23,
    title: 'Crabby Coder',
    description: 'Most Rust issues solved (2nd place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-05',
    category: 'lang_mastery',
    position: 1,
  },
  {
    id: 24,
    title: "2 Pincers n' Maximum Effort",
    description: 'Most Rust issues solved (1st place).',
    icon: '/Badges/',
    unlocked: false,
    tier: 'gold',
    progress: 40,
    category: 'lang_mastery',
    position: 2,
    requires: [23],
  },

  // Seasonal Badges - Zig
  {
    id: 25,
    title: "Salamander's Totem",
    description: 'Most Zig issues solved (2nd place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-04',
    category: 'lang_mastery',
    position: 3,
  },
  {
    id: 26,
    title: "Salamander's Spirit",
    description: 'Most Zig issues solved (1st place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'gold',
    date: '2025-05-05',
    category: 'lang_mastery',
    position: 4,
    requires: [25],
  },

  // Seasonal Badges - Python
  {
    id: 27,
    title: 'Basilisk Defanged',
    description: 'Most Python issues solved (2nd place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-03',
    category: 'lang_mastery',
    position: 5,
  },
  {
    id: 28,
    title: 'Mamba Mentality',
    description: 'Most Python issues solved (1st place).',
    icon: '/Badges/',
    unlocked: false,
    tier: 'gold',
    progress: 50,
    category: 'lang_mastery',
    position: 6,
    requires: [27],
  },

  // Seasonal Badges - Go
  {
    id: 29,
    title: 'Primal Gopher',
    description: 'Most Go issues solved (2nd place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-03',
    category: 'lang_mastery',
    position: 7,
  },
  {
    id: 30,
    title: 'Apex Gopher',
    description: 'Most Go issues solved (1st place).',
    icon: '/Badges/',
    unlocked: false,
    tier: 'gold',
    progress: 20,
    category: 'lang_mastery',
    position: 8,
    requires: [29],
  },

  // Seasonal Badges - JS/TS
  {
    id: 31,
    title: 'Prop Driller',
    description: 'Most JS/TS issues solved (2nd place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'silver',
    date: '2025-05-03',
    category: 'lang_mastery',
    position: 9,
  },
  {
    id: 32,
    title: 'Forge Smelter',
    description: 'Most JS/TS issues solved (1st place).',
    icon: '/Badges/',
    unlocked: true,
    tier: 'gold',
    date: '2025-05-04',
    category: 'lang_mastery',
    position: 10,
    requires: [31],
  },

  // Streak Badges
  {
    id: 33,
    title: 'Lore Master',
    description: 'Make a submission accepted for each weekly challenge.',
    icon: '/Badges/',
    unlocked: false,
    tier: 'gold',
    progress: 90,
    category: 'mastery',
    position: 1,
  },
  {
    id: 34,
    title: 'Pirate of Issue-bians',
    description: 'Contribute to 10 issues in the same language.',
    icon: '/Badges/',
    unlocked: false,
    tier: 'silver',
    progress: 0,
    category: 'mastery',
    position: 2,
  },
  {
    id: 35,
    title: 'Enamoured',
    description: 'Got a PR accepted every week for a month.',
    icon: '/Badges/',
    unlocked: false,
    tier: 'bronze',
    progress: 0,
    category: 'mastery',
    position: 3,
  },
];
